version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - mysql_dados:/var/lib/mysql

volumes:
  mysql_dados: